### ISSUE TITLE
Error running example because no directory "out"

### ISSUE THREAD

**Issue by lukealanjohnson** [USNavalResearchLaboratory/SeaRay#2]
I followed the steps in https://searay.readthedocs.io/en/latest/run-desktop.html and when I got to 

     `python rays.py run device=xeon`

I got an error about there not being a directory `out`. I manually created `out` in the `rayroot` and then reran the above command and things worked.

**Comment by dfgordon** [comment]
Code will now create the requested output directory in case it does not already exist.
